# Docker Compose file for Fleet Management System

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: fleet-management
        container_name: fleet-management-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/node_modules
        networks:
            - fleet-network
        depends_on:
            db:
                condition: service_healthy
        environment:
            - APP_ENV=production
            - DB_HOST=db
            - DB_DATABASE=fleet_management
            - DB_USERNAME=fleet_user
            - DB_PASSWORD=root
            - REDIS_HOST=redis

    webserver:
        image: nginx:alpine
        container_name: fleet-management-webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www:ro
            - ./docker/nginx:/etc/nginx/conf.d:ro
        networks:
            - fleet-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: fleet-management-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: fleet_management
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: fleet_user
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        ports:
            - "3307:3307"
        networks:
            - fleet-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            interval: 10s

    redis:
        image: redis:alpine
        container_name: fleet-management-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - fleet-network
        volumes:
            - redis_data:/data

volumes:
    dbdata:
        driver: local
    redis_data:
        driver: local

networks:
    fleet-network:
        driver: bridge